// Generated by wrangler. DO NOT EDIT.
// Runtime types for the worker environment.

declare interface QueueBinding0 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch0 = { messages: unknown[]; queue: string };

declare interface QueueBinding1 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch1 = { messages: unknown[]; queue: string };

declare interface QueueBinding2 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch2 = { messages: unknown[]; queue: string };

declare interface QueueBinding3 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch3 = { messages: unknown[]; queue: string };

declare interface QueueBinding4 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch4 = { messages: unknown[]; queue: string };

declare interface QueueBinding5 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch5 = { messages: unknown[]; queue: string };

declare interface QueueBinding6 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch6 = { messages: unknown[]; queue: string };

declare interface QueueBinding7 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch7 = { messages: unknown[]; queue: string };

declare interface QueueBinding8 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch8 = { messages: unknown[]; queue: string };

declare interface QueueBinding9 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch9 = { messages: unknown[]; queue: string };

declare interface QueueBinding10 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch10 = { messages: unknown[]; queue: string };

declare interface QueueBinding11 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch11 = { messages: unknown[]; queue: string };

declare interface QueueBinding12 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch12 = { messages: unknown[]; queue: string };

declare interface QueueBinding13 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch13 = { messages: unknown[]; queue: string };

declare interface QueueBinding14 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch14 = { messages: unknown[]; queue: string };

declare interface QueueBinding15 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch15 = { messages: unknown[]; queue: string };

declare interface QueueBinding16 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch16 = { messages: unknown[]; queue: string };

declare interface QueueBinding17 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch17 = { messages: unknown[]; queue: string };

declare interface QueueBinding18 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch18 = { messages: unknown[]; queue: string };

declare interface QueueBinding19 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch19 = { messages: unknown[]; queue: string };

declare interface QueueBinding20 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch20 = { messages: unknown[]; queue: string };

declare interface QueueBinding21 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch21 = { messages: unknown[]; queue: string };

declare interface QueueBinding22 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch22 = { messages: unknown[]; queue: string };

declare interface QueueBinding23 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch23 = { messages: unknown[]; queue: string };

declare interface QueueBinding24 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch24 = { messages: unknown[]; queue: string };

declare interface QueueBinding25 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch25 = { messages: unknown[]; queue: string };

declare interface QueueBinding26 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch26 = { messages: unknown[]; queue: string };

declare interface QueueBinding27 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch27 = { messages: unknown[]; queue: string };

declare interface QueueBinding28 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch28 = { messages: unknown[]; queue: string };

declare interface QueueBinding29 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch29 = { messages: unknown[]; queue: string };

declare interface QueueBinding30 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch30 = { messages: unknown[]; queue: string };

declare interface QueueBinding31 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch31 = { messages: unknown[]; queue: string };

declare interface QueueBinding32 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch32 = { messages: unknown[]; queue: string };

declare interface QueueBinding33 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch33 = { messages: unknown[]; queue: string };

declare interface QueueBinding34 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch34 = { messages: unknown[]; queue: string };

declare interface QueueBinding35 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch35 = { messages: unknown[]; queue: string };

declare interface QueueBinding36 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch36 = { messages: unknown[]; queue: string };

declare interface QueueBinding37 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch37 = { messages: unknown[]; queue: string };

declare interface QueueBinding38 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch38 = { messages: unknown[]; queue: string };

declare interface QueueBinding39 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch39 = { messages: unknown[]; queue: string };

declare interface QueueBinding40 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch40 = { messages: unknown[]; queue: string };

declare interface QueueBinding41 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch41 = { messages: unknown[]; queue: string };

declare interface QueueBinding42 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch42 = { messages: unknown[]; queue: string };

declare interface QueueBinding43 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch43 = { messages: unknown[]; queue: string };

declare interface QueueBinding44 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch44 = { messages: unknown[]; queue: string };

declare interface QueueBinding45 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch45 = { messages: unknown[]; queue: string };

declare interface QueueBinding46 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch46 = { messages: unknown[]; queue: string };

declare interface QueueBinding47 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch47 = { messages: unknown[]; queue: string };

declare interface QueueBinding48 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch48 = { messages: unknown[]; queue: string };

declare interface QueueBinding49 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch49 = { messages: unknown[]; queue: string };

declare interface QueueBinding50 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch50 = { messages: unknown[]; queue: string };

declare interface QueueBinding51 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch51 = { messages: unknown[]; queue: string };

declare interface QueueBinding52 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch52 = { messages: unknown[]; queue: string };

declare interface QueueBinding53 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch53 = { messages: unknown[]; queue: string };

declare interface QueueBinding54 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch54 = { messages: unknown[]; queue: string };

declare interface QueueBinding55 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch55 = { messages: unknown[]; queue: string };

declare interface QueueBinding56 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch56 = { messages: unknown[]; queue: string };

declare interface QueueBinding57 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch57 = { messages: unknown[]; queue: string };

declare interface QueueBinding58 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch58 = { messages: unknown[]; queue: string };

declare interface QueueBinding59 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch59 = { messages: unknown[]; queue: string };

declare interface QueueBinding60 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch60 = { messages: unknown[]; queue: string };

declare interface QueueBinding61 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch61 = { messages: unknown[]; queue: string };

declare interface QueueBinding62 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch62 = { messages: unknown[]; queue: string };

declare interface QueueBinding63 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch63 = { messages: unknown[]; queue: string };

declare interface QueueBinding64 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch64 = { messages: unknown[]; queue: string };

declare interface QueueBinding65 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch65 = { messages: unknown[]; queue: string };

declare interface QueueBinding66 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch66 = { messages: unknown[]; queue: string };

declare interface QueueBinding67 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch67 = { messages: unknown[]; queue: string };

declare interface QueueBinding68 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch68 = { messages: unknown[]; queue: string };

declare interface QueueBinding69 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch69 = { messages: unknown[]; queue: string };

declare interface QueueBinding70 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch70 = { messages: unknown[]; queue: string };

declare interface QueueBinding71 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch71 = { messages: unknown[]; queue: string };

declare interface QueueBinding72 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch72 = { messages: unknown[]; queue: string };

declare interface QueueBinding73 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch73 = { messages: unknown[]; queue: string };

declare interface QueueBinding74 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch74 = { messages: unknown[]; queue: string };

declare interface QueueBinding75 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch75 = { messages: unknown[]; queue: string };

declare interface QueueBinding76 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch76 = { messages: unknown[]; queue: string };

declare interface QueueBinding77 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch77 = { messages: unknown[]; queue: string };

declare interface QueueBinding78 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch78 = { messages: unknown[]; queue: string };

declare interface QueueBinding79 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch79 = { messages: unknown[]; queue: string };

declare interface QueueBinding80 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch80 = { messages: unknown[]; queue: string };

declare interface QueueBinding81 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch81 = { messages: unknown[]; queue: string };

declare interface QueueBinding82 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch82 = { messages: unknown[]; queue: string };

declare interface QueueBinding83 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch83 = { messages: unknown[]; queue: string };

declare interface QueueBinding84 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch84 = { messages: unknown[]; queue: string };

declare interface QueueBinding85 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch85 = { messages: unknown[]; queue: string };

declare interface QueueBinding86 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch86 = { messages: unknown[]; queue: string };

declare interface QueueBinding87 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch87 = { messages: unknown[]; queue: string };

declare interface QueueBinding88 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch88 = { messages: unknown[]; queue: string };

declare interface QueueBinding89 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch89 = { messages: unknown[]; queue: string };

declare interface QueueBinding90 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch90 = { messages: unknown[]; queue: string };

declare interface QueueBinding91 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch91 = { messages: unknown[]; queue: string };

declare interface QueueBinding92 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch92 = { messages: unknown[]; queue: string };

declare interface QueueBinding93 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch93 = { messages: unknown[]; queue: string };

declare interface QueueBinding94 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch94 = { messages: unknown[]; queue: string };

declare interface QueueBinding95 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch95 = { messages: unknown[]; queue: string };

declare interface QueueBinding96 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch96 = { messages: unknown[]; queue: string };

declare interface QueueBinding97 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch97 = { messages: unknown[]; queue: string };

declare interface QueueBinding98 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch98 = { messages: unknown[]; queue: string };

declare interface QueueBinding99 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch99 = { messages: unknown[]; queue: string };

declare interface QueueBinding100 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch100 = { messages: unknown[]; queue: string };

declare interface QueueBinding101 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch101 = { messages: unknown[]; queue: string };

declare interface QueueBinding102 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch102 = { messages: unknown[]; queue: string };

declare interface QueueBinding103 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch103 = { messages: unknown[]; queue: string };

declare interface QueueBinding104 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch104 = { messages: unknown[]; queue: string };

declare interface QueueBinding105 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch105 = { messages: unknown[]; queue: string };

declare interface QueueBinding106 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch106 = { messages: unknown[]; queue: string };

declare interface QueueBinding107 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch107 = { messages: unknown[]; queue: string };

declare interface QueueBinding108 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch108 = { messages: unknown[]; queue: string };

declare interface QueueBinding109 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch109 = { messages: unknown[]; queue: string };

declare interface QueueBinding110 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch110 = { messages: unknown[]; queue: string };

declare interface QueueBinding111 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch111 = { messages: unknown[]; queue: string };

declare interface QueueBinding112 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch112 = { messages: unknown[]; queue: string };

declare interface QueueBinding113 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch113 = { messages: unknown[]; queue: string };

declare interface QueueBinding114 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch114 = { messages: unknown[]; queue: string };

declare interface QueueBinding115 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch115 = { messages: unknown[]; queue: string };

declare interface QueueBinding116 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch116 = { messages: unknown[]; queue: string };

declare interface QueueBinding117 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch117 = { messages: unknown[]; queue: string };

declare interface QueueBinding118 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch118 = { messages: unknown[]; queue: string };

declare interface QueueBinding119 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch119 = { messages: unknown[]; queue: string };

declare interface QueueBinding120 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch120 = { messages: unknown[]; queue: string };

declare interface QueueBinding121 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch121 = { messages: unknown[]; queue: string };

declare interface QueueBinding122 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch122 = { messages: unknown[]; queue: string };

declare interface QueueBinding123 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch123 = { messages: unknown[]; queue: string };

declare interface QueueBinding124 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch124 = { messages: unknown[]; queue: string };

declare interface QueueBinding125 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch125 = { messages: unknown[]; queue: string };

declare interface QueueBinding126 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch126 = { messages: unknown[]; queue: string };

declare interface QueueBinding127 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch127 = { messages: unknown[]; queue: string };

declare interface QueueBinding128 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch128 = { messages: unknown[]; queue: string };

declare interface QueueBinding129 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch129 = { messages: unknown[]; queue: string };

declare interface QueueBinding130 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch130 = { messages: unknown[]; queue: string };

declare interface QueueBinding131 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch131 = { messages: unknown[]; queue: string };

declare interface QueueBinding132 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch132 = { messages: unknown[]; queue: string };

declare interface QueueBinding133 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch133 = { messages: unknown[]; queue: string };

declare interface QueueBinding134 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch134 = { messages: unknown[]; queue: string };

declare interface QueueBinding135 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch135 = { messages: unknown[]; queue: string };

declare interface QueueBinding136 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch136 = { messages: unknown[]; queue: string };

declare interface QueueBinding137 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch137 = { messages: unknown[]; queue: string };

declare interface QueueBinding138 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch138 = { messages: unknown[]; queue: string };

declare interface QueueBinding139 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch139 = { messages: unknown[]; queue: string };

declare interface QueueBinding140 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch140 = { messages: unknown[]; queue: string };

declare interface QueueBinding141 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch141 = { messages: unknown[]; queue: string };

declare interface QueueBinding142 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch142 = { messages: unknown[]; queue: string };

declare interface QueueBinding143 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch143 = { messages: unknown[]; queue: string };

declare interface QueueBinding144 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch144 = { messages: unknown[]; queue: string };

declare interface QueueBinding145 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch145 = { messages: unknown[]; queue: string };

declare interface QueueBinding146 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch146 = { messages: unknown[]; queue: string };

declare interface QueueBinding147 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch147 = { messages: unknown[]; queue: string };

declare interface QueueBinding148 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch148 = { messages: unknown[]; queue: string };

declare interface QueueBinding149 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch149 = { messages: unknown[]; queue: string };

declare interface QueueBinding150 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch150 = { messages: unknown[]; queue: string };

declare interface QueueBinding151 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch151 = { messages: unknown[]; queue: string };

declare interface QueueBinding152 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch152 = { messages: unknown[]; queue: string };

declare interface QueueBinding153 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch153 = { messages: unknown[]; queue: string };

declare interface QueueBinding154 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch154 = { messages: unknown[]; queue: string };

declare interface QueueBinding155 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch155 = { messages: unknown[]; queue: string };

declare interface QueueBinding156 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch156 = { messages: unknown[]; queue: string };

declare interface QueueBinding157 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch157 = { messages: unknown[]; queue: string };

declare interface QueueBinding158 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch158 = { messages: unknown[]; queue: string };

declare interface QueueBinding159 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch159 = { messages: unknown[]; queue: string };

declare interface QueueBinding160 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch160 = { messages: unknown[]; queue: string };

declare interface QueueBinding161 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch161 = { messages: unknown[]; queue: string };

declare interface QueueBinding162 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch162 = { messages: unknown[]; queue: string };

declare interface QueueBinding163 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch163 = { messages: unknown[]; queue: string };

declare interface QueueBinding164 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch164 = { messages: unknown[]; queue: string };

declare interface QueueBinding165 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch165 = { messages: unknown[]; queue: string };

declare interface QueueBinding166 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch166 = { messages: unknown[]; queue: string };

declare interface QueueBinding167 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch167 = { messages: unknown[]; queue: string };

declare interface QueueBinding168 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch168 = { messages: unknown[]; queue: string };

declare interface QueueBinding169 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch169 = { messages: unknown[]; queue: string };

declare interface QueueBinding170 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch170 = { messages: unknown[]; queue: string };

declare interface QueueBinding171 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch171 = { messages: unknown[]; queue: string };

declare interface QueueBinding172 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch172 = { messages: unknown[]; queue: string };

declare interface QueueBinding173 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch173 = { messages: unknown[]; queue: string };

declare interface QueueBinding174 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch174 = { messages: unknown[]; queue: string };

declare interface QueueBinding175 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch175 = { messages: unknown[]; queue: string };

declare interface QueueBinding176 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch176 = { messages: unknown[]; queue: string };

declare interface QueueBinding177 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch177 = { messages: unknown[]; queue: string };

declare interface QueueBinding178 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch178 = { messages: unknown[]; queue: string };

declare interface QueueBinding179 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch179 = { messages: unknown[]; queue: string };

declare interface QueueBinding180 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch180 = { messages: unknown[]; queue: string };

declare interface QueueBinding181 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch181 = { messages: unknown[]; queue: string };

declare interface QueueBinding182 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch182 = { messages: unknown[]; queue: string };

declare interface QueueBinding183 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch183 = { messages: unknown[]; queue: string };

declare interface QueueBinding184 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch184 = { messages: unknown[]; queue: string };

declare interface QueueBinding185 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch185 = { messages: unknown[]; queue: string };

declare interface QueueBinding186 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch186 = { messages: unknown[]; queue: string };

declare interface QueueBinding187 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch187 = { messages: unknown[]; queue: string };

declare interface QueueBinding188 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch188 = { messages: unknown[]; queue: string };

declare interface QueueBinding189 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch189 = { messages: unknown[]; queue: string };

declare interface QueueBinding190 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch190 = { messages: unknown[]; queue: string };

declare interface QueueBinding191 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch191 = { messages: unknown[]; queue: string };

declare interface QueueBinding192 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch192 = { messages: unknown[]; queue: string };

declare interface QueueBinding193 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch193 = { messages: unknown[]; queue: string };

declare interface QueueBinding194 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch194 = { messages: unknown[]; queue: string };

declare interface QueueBinding195 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch195 = { messages: unknown[]; queue: string };

declare interface QueueBinding196 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch196 = { messages: unknown[]; queue: string };

declare interface QueueBinding197 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch197 = { messages: unknown[]; queue: string };

declare interface QueueBinding198 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch198 = { messages: unknown[]; queue: string };

declare interface QueueBinding199 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch199 = { messages: unknown[]; queue: string };

declare interface QueueBinding200 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch200 = { messages: unknown[]; queue: string };

declare interface QueueBinding201 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch201 = { messages: unknown[]; queue: string };

declare interface QueueBinding202 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch202 = { messages: unknown[]; queue: string };

declare interface QueueBinding203 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch203 = { messages: unknown[]; queue: string };

declare interface QueueBinding204 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch204 = { messages: unknown[]; queue: string };

declare interface QueueBinding205 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch205 = { messages: unknown[]; queue: string };

declare interface QueueBinding206 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch206 = { messages: unknown[]; queue: string };

declare interface QueueBinding207 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch207 = { messages: unknown[]; queue: string };

declare interface QueueBinding208 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch208 = { messages: unknown[]; queue: string };

declare interface QueueBinding209 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch209 = { messages: unknown[]; queue: string };

declare interface QueueBinding210 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch210 = { messages: unknown[]; queue: string };

declare interface QueueBinding211 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch211 = { messages: unknown[]; queue: string };

declare interface QueueBinding212 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch212 = { messages: unknown[]; queue: string };

declare interface QueueBinding213 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch213 = { messages: unknown[]; queue: string };

declare interface QueueBinding214 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch214 = { messages: unknown[]; queue: string };

declare interface QueueBinding215 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch215 = { messages: unknown[]; queue: string };

declare interface QueueBinding216 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch216 = { messages: unknown[]; queue: string };

declare interface QueueBinding217 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch217 = { messages: unknown[]; queue: string };

declare interface QueueBinding218 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch218 = { messages: unknown[]; queue: string };

declare interface QueueBinding219 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch219 = { messages: unknown[]; queue: string };

declare interface QueueBinding220 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch220 = { messages: unknown[]; queue: string };

declare interface QueueBinding221 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch221 = { messages: unknown[]; queue: string };

declare interface QueueBinding222 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch222 = { messages: unknown[]; queue: string };

declare interface QueueBinding223 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch223 = { messages: unknown[]; queue: string };

declare interface QueueBinding224 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch224 = { messages: unknown[]; queue: string };

declare interface QueueBinding225 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch225 = { messages: unknown[]; queue: string };

declare interface QueueBinding226 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch226 = { messages: unknown[]; queue: string };

declare interface QueueBinding227 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch227 = { messages: unknown[]; queue: string };

declare interface QueueBinding228 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch228 = { messages: unknown[]; queue: string };

declare interface QueueBinding229 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch229 = { messages: unknown[]; queue: string };

declare interface QueueBinding230 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch230 = { messages: unknown[]; queue: string };

declare interface QueueBinding231 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch231 = { messages: unknown[]; queue: string };

declare interface QueueBinding232 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch232 = { messages: unknown[]; queue: string };

declare interface QueueBinding233 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch233 = { messages: unknown[]; queue: string };

declare interface QueueBinding234 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch234 = { messages: unknown[]; queue: string };

declare interface QueueBinding235 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch235 = { messages: unknown[]; queue: string };

declare interface QueueBinding236 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch236 = { messages: unknown[]; queue: string };

declare interface QueueBinding237 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch237 = { messages: unknown[]; queue: string };

declare interface QueueBinding238 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch238 = { messages: unknown[]; queue: string };

declare interface QueueBinding239 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch239 = { messages: unknown[]; queue: string };

declare interface QueueBinding240 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch240 = { messages: unknown[]; queue: string };

declare interface QueueBinding241 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch241 = { messages: unknown[]; queue: string };

declare interface QueueBinding242 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch242 = { messages: unknown[]; queue: string };

declare interface QueueBinding243 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch243 = { messages: unknown[]; queue: string };

declare interface QueueBinding244 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch244 = { messages: unknown[]; queue: string };

declare interface QueueBinding245 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch245 = { messages: unknown[]; queue: string };

declare interface QueueBinding246 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch246 = { messages: unknown[]; queue: string };

declare interface QueueBinding247 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch247 = { messages: unknown[]; queue: string };

declare interface QueueBinding248 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch248 = { messages: unknown[]; queue: string };

declare interface QueueBinding249 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch249 = { messages: unknown[]; queue: string };

declare interface QueueBinding250 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch250 = { messages: unknown[]; queue: string };

declare interface QueueBinding251 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch251 = { messages: unknown[]; queue: string };

declare interface QueueBinding252 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch252 = { messages: unknown[]; queue: string };

declare interface QueueBinding253 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch253 = { messages: unknown[]; queue: string };

declare interface QueueBinding254 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch254 = { messages: unknown[]; queue: string };

declare interface QueueBinding255 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch255 = { messages: unknown[]; queue: string };

declare interface QueueBinding256 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch256 = { messages: unknown[]; queue: string };

declare interface QueueBinding257 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch257 = { messages: unknown[]; queue: string };

declare interface QueueBinding258 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch258 = { messages: unknown[]; queue: string };

declare interface QueueBinding259 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch259 = { messages: unknown[]; queue: string };

declare interface QueueBinding260 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch260 = { messages: unknown[]; queue: string };

declare interface QueueBinding261 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch261 = { messages: unknown[]; queue: string };

declare interface QueueBinding262 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch262 = { messages: unknown[]; queue: string };

declare interface QueueBinding263 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch263 = { messages: unknown[]; queue: string };

declare interface QueueBinding264 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch264 = { messages: unknown[]; queue: string };

declare interface QueueBinding265 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch265 = { messages: unknown[]; queue: string };

declare interface QueueBinding266 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch266 = { messages: unknown[]; queue: string };

declare interface QueueBinding267 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch267 = { messages: unknown[]; queue: string };

declare interface QueueBinding268 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch268 = { messages: unknown[]; queue: string };

declare interface QueueBinding269 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch269 = { messages: unknown[]; queue: string };

declare interface QueueBinding270 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch270 = { messages: unknown[]; queue: string };

declare interface QueueBinding271 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch271 = { messages: unknown[]; queue: string };

declare interface QueueBinding272 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch272 = { messages: unknown[]; queue: string };

declare interface QueueBinding273 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch273 = { messages: unknown[]; queue: string };

declare interface QueueBinding274 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch274 = { messages: unknown[]; queue: string };

declare interface QueueBinding275 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch275 = { messages: unknown[]; queue: string };

declare interface QueueBinding276 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch276 = { messages: unknown[]; queue: string };

declare interface QueueBinding277 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch277 = { messages: unknown[]; queue: string };

declare interface QueueBinding278 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch278 = { messages: unknown[]; queue: string };

declare interface QueueBinding279 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch279 = { messages: unknown[]; queue: string };

declare interface QueueBinding280 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch280 = { messages: unknown[]; queue: string };

declare interface QueueBinding281 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch281 = { messages: unknown[]; queue: string };

declare interface QueueBinding282 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch282 = { messages: unknown[]; queue: string };

declare interface QueueBinding283 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch283 = { messages: unknown[]; queue: string };

declare interface QueueBinding284 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch284 = { messages: unknown[]; queue: string };

declare interface QueueBinding285 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch285 = { messages: unknown[]; queue: string };

declare interface QueueBinding286 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch286 = { messages: unknown[]; queue: string };

declare interface QueueBinding287 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch287 = { messages: unknown[]; queue: string };

declare interface QueueBinding288 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch288 = { messages: unknown[]; queue: string };

declare interface QueueBinding289 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch289 = { messages: unknown[]; queue: string };

declare interface QueueBinding290 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch290 = { messages: unknown[]; queue: string };

declare interface QueueBinding291 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch291 = { messages: unknown[]; queue: string };

declare interface QueueBinding292 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch292 = { messages: unknown[]; queue: string };

declare interface QueueBinding293 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch293 = { messages: unknown[]; queue: string };

declare interface QueueBinding294 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch294 = { messages: unknown[]; queue: string };

declare interface QueueBinding295 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch295 = { messages: unknown[]; queue: string };

declare interface QueueBinding296 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch296 = { messages: unknown[]; queue: string };

declare interface QueueBinding297 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch297 = { messages: unknown[]; queue: string };

declare interface QueueBinding298 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch298 = { messages: unknown[]; queue: string };

declare interface QueueBinding299 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch299 = { messages: unknown[]; queue: string };

declare interface QueueBinding300 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch300 = { messages: unknown[]; queue: string };

declare interface QueueBinding301 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch301 = { messages: unknown[]; queue: string };

declare interface QueueBinding302 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch302 = { messages: unknown[]; queue: string };

declare interface QueueBinding303 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch303 = { messages: unknown[]; queue: string };

declare interface QueueBinding304 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch304 = { messages: unknown[]; queue: string };

declare interface QueueBinding305 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch305 = { messages: unknown[]; queue: string };

declare interface QueueBinding306 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch306 = { messages: unknown[]; queue: string };

declare interface QueueBinding307 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch307 = { messages: unknown[]; queue: string };

declare interface QueueBinding308 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch308 = { messages: unknown[]; queue: string };

declare interface QueueBinding309 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch309 = { messages: unknown[]; queue: string };

declare interface QueueBinding310 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch310 = { messages: unknown[]; queue: string };

declare interface QueueBinding311 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch311 = { messages: unknown[]; queue: string };

declare interface QueueBinding312 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch312 = { messages: unknown[]; queue: string };

declare interface QueueBinding313 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch313 = { messages: unknown[]; queue: string };

declare interface QueueBinding314 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch314 = { messages: unknown[]; queue: string };

declare interface QueueBinding315 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch315 = { messages: unknown[]; queue: string };

declare interface QueueBinding316 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch316 = { messages: unknown[]; queue: string };

declare interface QueueBinding317 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch317 = { messages: unknown[]; queue: string };

declare interface QueueBinding318 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch318 = { messages: unknown[]; queue: string };

declare interface QueueBinding319 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch319 = { messages: unknown[]; queue: string };

declare interface QueueBinding320 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch320 = { messages: unknown[]; queue: string };

declare interface QueueBinding321 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch321 = { messages: unknown[]; queue: string };

declare interface QueueBinding322 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch322 = { messages: unknown[]; queue: string };

declare interface QueueBinding323 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch323 = { messages: unknown[]; queue: string };

declare interface QueueBinding324 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch324 = { messages: unknown[]; queue: string };

declare interface QueueBinding325 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch325 = { messages: unknown[]; queue: string };

declare interface QueueBinding326 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch326 = { messages: unknown[]; queue: string };

declare interface QueueBinding327 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch327 = { messages: unknown[]; queue: string };

declare interface QueueBinding328 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch328 = { messages: unknown[]; queue: string };

declare interface QueueBinding329 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch329 = { messages: unknown[]; queue: string };

declare interface QueueBinding330 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch330 = { messages: unknown[]; queue: string };

declare interface QueueBinding331 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch331 = { messages: unknown[]; queue: string };

declare interface QueueBinding332 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch332 = { messages: unknown[]; queue: string };

declare interface QueueBinding333 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch333 = { messages: unknown[]; queue: string };

declare interface QueueBinding334 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch334 = { messages: unknown[]; queue: string };

declare interface QueueBinding335 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch335 = { messages: unknown[]; queue: string };

declare interface QueueBinding336 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch336 = { messages: unknown[]; queue: string };

declare interface QueueBinding337 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch337 = { messages: unknown[]; queue: string };

declare interface QueueBinding338 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch338 = { messages: unknown[]; queue: string };

declare interface QueueBinding339 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch339 = { messages: unknown[]; queue: string };

declare interface QueueBinding340 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch340 = { messages: unknown[]; queue: string };

declare interface QueueBinding341 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch341 = { messages: unknown[]; queue: string };

declare interface QueueBinding342 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch342 = { messages: unknown[]; queue: string };

declare interface QueueBinding343 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch343 = { messages: unknown[]; queue: string };

declare interface QueueBinding344 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch344 = { messages: unknown[]; queue: string };

declare interface QueueBinding345 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch345 = { messages: unknown[]; queue: string };

declare interface QueueBinding346 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch346 = { messages: unknown[]; queue: string };

declare interface QueueBinding347 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch347 = { messages: unknown[]; queue: string };

declare interface QueueBinding348 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch348 = { messages: unknown[]; queue: string };

declare interface QueueBinding349 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch349 = { messages: unknown[]; queue: string };

declare interface QueueBinding350 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch350 = { messages: unknown[]; queue: string };

declare interface QueueBinding351 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch351 = { messages: unknown[]; queue: string };

declare interface QueueBinding352 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch352 = { messages: unknown[]; queue: string };

declare interface QueueBinding353 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch353 = { messages: unknown[]; queue: string };

declare interface QueueBinding354 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch354 = { messages: unknown[]; queue: string };

declare interface QueueBinding355 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch355 = { messages: unknown[]; queue: string };

declare interface QueueBinding356 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch356 = { messages: unknown[]; queue: string };

declare interface QueueBinding357 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch357 = { messages: unknown[]; queue: string };

declare interface QueueBinding358 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch358 = { messages: unknown[]; queue: string };

declare interface QueueBinding359 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch359 = { messages: unknown[]; queue: string };

declare interface QueueBinding360 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch360 = { messages: unknown[]; queue: string };

declare interface QueueBinding361 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch361 = { messages: unknown[]; queue: string };

declare interface QueueBinding362 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch362 = { messages: unknown[]; queue: string };

declare interface QueueBinding363 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch363 = { messages: unknown[]; queue: string };

declare interface QueueBinding364 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch364 = { messages: unknown[]; queue: string };

declare interface QueueBinding365 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch365 = { messages: unknown[]; queue: string };

declare interface QueueBinding366 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch366 = { messages: unknown[]; queue: string };

declare interface QueueBinding367 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch367 = { messages: unknown[]; queue: string };

declare interface QueueBinding368 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch368 = { messages: unknown[]; queue: string };

declare interface QueueBinding369 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch369 = { messages: unknown[]; queue: string };

declare interface QueueBinding370 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch370 = { messages: unknown[]; queue: string };

declare interface QueueBinding371 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch371 = { messages: unknown[]; queue: string };

declare interface QueueBinding372 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch372 = { messages: unknown[]; queue: string };

declare interface QueueBinding373 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch373 = { messages: unknown[]; queue: string };

declare interface QueueBinding374 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch374 = { messages: unknown[]; queue: string };

declare interface QueueBinding375 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch375 = { messages: unknown[]; queue: string };

declare interface QueueBinding376 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch376 = { messages: unknown[]; queue: string };

declare interface QueueBinding377 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch377 = { messages: unknown[]; queue: string };

declare interface QueueBinding378 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch378 = { messages: unknown[]; queue: string };

declare interface QueueBinding379 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch379 = { messages: unknown[]; queue: string };

declare interface QueueBinding380 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch380 = { messages: unknown[]; queue: string };

declare interface QueueBinding381 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch381 = { messages: unknown[]; queue: string };

declare interface QueueBinding382 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch382 = { messages: unknown[]; queue: string };

declare interface QueueBinding383 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch383 = { messages: unknown[]; queue: string };

declare interface QueueBinding384 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch384 = { messages: unknown[]; queue: string };

declare interface QueueBinding385 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch385 = { messages: unknown[]; queue: string };

declare interface QueueBinding386 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch386 = { messages: unknown[]; queue: string };

declare interface QueueBinding387 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch387 = { messages: unknown[]; queue: string };

declare interface QueueBinding388 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch388 = { messages: unknown[]; queue: string };

declare interface QueueBinding389 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch389 = { messages: unknown[]; queue: string };

declare interface QueueBinding390 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch390 = { messages: unknown[]; queue: string };

declare interface QueueBinding391 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch391 = { messages: unknown[]; queue: string };

declare interface QueueBinding392 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch392 = { messages: unknown[]; queue: string };

declare interface QueueBinding393 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch393 = { messages: unknown[]; queue: string };

declare interface QueueBinding394 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch394 = { messages: unknown[]; queue: string };

declare interface QueueBinding395 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch395 = { messages: unknown[]; queue: string };

declare interface QueueBinding396 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch396 = { messages: unknown[]; queue: string };

declare interface QueueBinding397 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch397 = { messages: unknown[]; queue: string };

declare interface QueueBinding398 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch398 = { messages: unknown[]; queue: string };

declare interface QueueBinding399 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch399 = { messages: unknown[]; queue: string };

declare interface QueueBinding400 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch400 = { messages: unknown[]; queue: string };

declare interface QueueBinding401 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch401 = { messages: unknown[]; queue: string };

declare interface QueueBinding402 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch402 = { messages: unknown[]; queue: string };

declare interface QueueBinding403 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch403 = { messages: unknown[]; queue: string };

declare interface QueueBinding404 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch404 = { messages: unknown[]; queue: string };

declare interface QueueBinding405 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch405 = { messages: unknown[]; queue: string };

declare interface QueueBinding406 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch406 = { messages: unknown[]; queue: string };

declare interface QueueBinding407 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch407 = { messages: unknown[]; queue: string };

declare interface QueueBinding408 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch408 = { messages: unknown[]; queue: string };

declare interface QueueBinding409 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch409 = { messages: unknown[]; queue: string };

declare interface QueueBinding410 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch410 = { messages: unknown[]; queue: string };

declare interface QueueBinding411 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch411 = { messages: unknown[]; queue: string };

declare interface QueueBinding412 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch412 = { messages: unknown[]; queue: string };

declare interface QueueBinding413 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch413 = { messages: unknown[]; queue: string };

declare interface QueueBinding414 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch414 = { messages: unknown[]; queue: string };

declare interface QueueBinding415 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch415 = { messages: unknown[]; queue: string };

declare interface QueueBinding416 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch416 = { messages: unknown[]; queue: string };

declare interface QueueBinding417 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch417 = { messages: unknown[]; queue: string };

declare interface QueueBinding418 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch418 = { messages: unknown[]; queue: string };

declare interface QueueBinding419 {
	send(message: unknown): Promise<void>;
	sendBatch(messages: unknown[]): Promise<void>;
}
declare type QueuedMessageBatch419 = { messages: unknown[]; queue: string };

declare global {
	interface Env { QUEUE: QueueBinding0 }
}
export {};
